# Generated by Django 3.2.9 on 2022-02-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marcasvehiculo',
        ),
        migrations.DeleteModel(
            name='vendedore',
        ),
        migrations.DeleteModel(
            name='venta',
        ),
    ]
