# Generated by Django 3.2.9 on 2022-02-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasblog', '0003_duenios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duenios',
            new_name='Duenio',
        ),
        migrations.RenameModel(
            old_name='Mascotas',
            new_name='Mascota',
        ),
    ]
