# Generated by Django 3.2.9 on 2022-02-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasblog', '0004_auto_20220224_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duenio',
            old_name='anios',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='anios',
            new_name='edad',
        ),
    ]
