# Generated by Django 3.2.9 on 2022-02-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasblog', '0005_auto_20220224_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='trucos',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
