# Generated by Django 3.2.9 on 2022-02-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasblog', '0006_mascota_trucos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
