# Generated by Django 4.0 on 2022-02-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotasblog', '0007_ropita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marcasvehiculo',
        ),
        migrations.DeleteModel(
            name='vendedore',
        ),
        migrations.DeleteModel(
            name='venta',
        ),
    ]
